/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.habitat.PresentationLayer.Candidaturas.Projectos;

import com.habitat.BusinessLayer.BusinessFacade;
import com.habitat.BusinessLayer.Projetos.Projeto;
import com.habitat.BusinessLayer.Projetos.ProjetoTarefas;
import com.habitat.util.ErrorWindow;
import java.sql.Date;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author xavier
 */
public class AddProjectoJP extends javax.swing.JPanel implements Observer {

    /**
     * Creates new form addProjectoJP
     */
    private BusinessFacade bus;
    private ArrayList<String> candidaturas;
    public AddProjectoJP(BusinessFacade b) {
        try{
            this.bus = b;
            this.candidaturas = bus.getIdCandidaturasSemProjecto();
            this.bus.addObserver(this);
            initComponents();
            updateComboBox();
        }catch (SQLException ex) {
            Logger.getLogger(AddProjectoJP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void updateComboBox(){
        this.candidaturaCB.removeAllItems();
        for(String s : this.candidaturas){
            this.candidaturaCB.addItem(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        candidaturaCB = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricao_ta = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addProjectoBT = new javax.swing.JButton();
        data_tf = new javax.swing.JFormattedTextField();
        orcamento_tf = new javax.swing.JFormattedTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Adiciona Projeto"));

        candidaturaCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        candidaturaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidaturaCBActionPerformed(evt);
            }
        });

        jLabel1.setText("Candidatura");

        jLabel2.setText("Data de Início:");

        jLabel3.setText("Descrição:");

        descricao_ta.setColumns(20);
        descricao_ta.setRows(5);
        jScrollPane1.setViewportView(descricao_ta);

        jLabel4.setText("Orçamento:");

        jLabel5.setText("(EUR)");

        addProjectoBT.setText("Adicionar");
        addProjectoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProjectoBTActionPerformed(evt);
            }
        });

        try {
            data_tf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        orcamento_tf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(candidaturaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(data_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(addProjectoBT)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(orcamento_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(candidaturaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(data_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(orcamento_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(addProjectoBT)
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void candidaturaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidaturaCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_candidaturaCBActionPerformed

    private void addProjectoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProjectoBTActionPerformed
        // TODO add your handling code here:
        Projeto p;
        String cand;
        String c = ((String) this.candidaturaCB.getSelectedItem());
        if(c == null)
            {new ErrorWindow("Projeto","Candidatura não Encontrada", "warning", new JFrame()).wshow();
            return;}
        else{
            String [] parse =c.split(":");
            cand = parse[0];
            System.out.println("candidatura "+ cand);
        }
        String[] dateArr = this.data_tf.getText().split("/");
        Date date = new Date(Integer.parseInt(dateArr[2]) - 1900, Integer.parseInt(dateArr[1]) - 1,
                Integer.parseInt(dateArr[0]));
        String val_s = this.orcamento_tf.getText();
        double d = Double.parseDouble(val_s.replace(",", "."));
//(String cod,String cand, Date _dataI, Date _dataF, String _estado,
//String _descricao, double _orcamento, String Funcionario, ArrayList<ProjetoTarefas> tarefas)
        p = new Projeto("",cand,date,date,"iniciado",this.descricao_ta.getText(),
                        d,this.bus.getActiveUser().getUsername(),new ArrayList<ProjetoTarefas>());
        try {
            this.bus.addProjeto(p);
        } catch (SQLException ex) {
            Logger.getLogger(AddProjectoJP.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.data_tf.setText("");
        this.descricao_ta.setText("");
        this.orcamento_tf.setText("");
        
    }//GEN-LAST:event_addProjectoBTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProjectoBT;
    private javax.swing.JComboBox candidaturaCB;
    private javax.swing.JFormattedTextField data_tf;
    private javax.swing.JTextArea descricao_ta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField orcamento_tf;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        try {
            this.candidaturas = bus.getIdCandidaturasSemProjecto();
        } catch (SQLException ex) {
            Logger.getLogger(AddProjectoJP.class.getName()).log(Level.SEVERE, null, ex);
        }
        updateComboBox();
    }
}
