/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.habitat.PresentationLayer.Doacoes;

import com.habitat.BusinessLayer.BusinessFacade;
import com.habitat.BusinessLayer.Doadores.DMaterial;
import com.habitat.BusinessLayer.Doadores.Doacao;
import com.habitat.BusinessLayer.Doadores.Monetario;
import com.habitat.BusinessLayer.Doadores.Servicos;
import java.awt.GridLayout;
import java.util.HashMap;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Pedro
 */
public class ConsDoacaoDialog extends javax.swing.JDialog {

    /**
     * Creates new form consDoacaoDialog
     * @param parent
     * @param modal
     */
    
    public ConsDoacaoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }
    public ConsDoacaoDialog(java.awt.Frame parent, boolean modal,Doacao d) {
        super(parent, modal);
        initComponents();
        DefaultTableModel model = ((DefaultTableModel)this.jTable1.getModel());
        if(d.getClass() == DMaterial.class){
                DMaterial dm = (DMaterial)d;
                model.addRow(new String[]{dm.getCod(),dm.getDescricao(),dm.getDate(),dm.getClass().getName(),null,""+dm.getQuantidade(),dm.getUnidade()});
            }
            
            if(d.getClass() == Monetario.class){
                Monetario m = (Monetario)d;
                model.addRow(new String[]{m.getCod(),m.getDate(),m.getDescricao(),m.getClass().getName(),String.valueOf(m.getValor()),null,null});
            }
            if(d.getClass() == Servicos.class){
                Servicos s = (Servicos)d;
                model.addRow(new String[]{s.getCod(),s.getDescricao(),s.getDate(),s.getClass().getName(),null,null,null});
            }
       
    }
    public ConsDoacaoDialog(java.awt.Frame parent, boolean modal,HashMap<String,Doacao> doacoes) {
        super(parent, modal);
        initComponents();
        
        DefaultTableModel model = ((DefaultTableModel)this.jTable1.getModel());
        for(Doacao d : doacoes.values())
        {
            if(d.getClass() == DMaterial.class){
                DMaterial dm = (DMaterial)d;
                model.addRow(new String[]{dm.getCod(),dm.getDescricao(),dm.getDate(),dm.getClass().getName(),null,""+dm.getQuantidade(),dm.getUnidade()});
            }
            
            if(d.getClass() == Monetario.class){
                Monetario m = (Monetario)d;
                model.addRow(new String[]{m.getCod(),m.getDate(),m.getDescricao(),m.getClass().getName(),String.valueOf(m.getValor()),null,null});
            }
            if(d.getClass() == Servicos.class){
                Servicos s = (Servicos)d;
                model.addRow(new String[]{s.getCod(),s.getDescricao(),s.getDate(),s.getClass().getName(),null,null,null});
            }
       
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descrição", "Data", "Tipo", "Montante", "Quantidade", "Unidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsDoacaoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsDoacaoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsDoacaoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsDoacaoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsDoacaoDialog dialog = new ConsDoacaoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
