/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.habitat.PresentationLayer;

import com.alee.laf.WebLookAndFeel;
import com.habitat.BusinessLayer.BusinessFacade;
import com.habitat.PresentationLayer.Candidaturas.CandidaturaJP;
import com.habitat.PresentationLayer.Doacoes.DoacoesJP;
import com.habitat.PresentationLayer.Doadores.DoadoresJP;
import com.habitat.PresentationLayer.Eventos.EventosJP;
import com.habitat.PresentationLayer.Funcionarios.FuncionariosJP;
import com.habitat.PresentationLayer.Inventario.InventarioJP;
import com.habitat.PresentationLayer.Voluntários.VoluntarioJP;
import static java.awt.SystemColor.desktop;

/**
 *
 * @author Pedro
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form HomeView
     * @param username
     */
    
    BusinessFacade businessFacade;
    public MainView(BusinessFacade bus) {
        this.businessFacade = bus;
        this.setTitle("Habitat");
        initComponents();
        this.init();
        this.setLocationByPlatform(true);
        
        
        
    }
    
    public MainView() {
        
        this.setTitle("Habitat");
        initComponents();
        this.init();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_tabs = new javax.swing.JTabbedPane();
        Home_jp = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name_label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        type_label = new javax.swing.JLabel();
        funcionarios_jp = new javax.swing.JPanel();
        candidaturas_jpanel = new javax.swing.JPanel();
        eventos_jp = new javax.swing.JPanel();
        doacoes_jp = new javax.swing.JPanel();
        doadoresJP = new javax.swing.JPanel();
        inventario_jp = new javax.swing.JPanel();
        voluntarios_jp = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        logout_bt = new javax.swing.JMenuItem();
        exit_bt = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main_tabs.setToolTipText("");
        main_tabs.setAlignmentX(0.0F);
        main_tabs.setAlignmentY(0.0F);
        main_tabs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        main_tabs.setFocusable(false);
        main_tabs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        main_tabs.setMaximumSize(new java.awt.Dimension(327670000, 327670000));
        main_tabs.setMinimumSize(new java.awt.Dimension(109, 148));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/habitat/PresentationLayer/ICONs/semFundo2.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Funcionário"));

        jLabel1.setText("Nome:");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/habitat/PresentationLayer/ICONs/user1.png"))); // NOI18N

        name_label.setText("nome asdasd");

        jLabel2.setText("Tipo :");

        type_label.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name_label))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(type_label)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(name_label))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(type_label)))
                    .addComponent(jLabel5))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Home_jpLayout = new javax.swing.GroupLayout(Home_jp);
        Home_jp.setLayout(Home_jpLayout);
        Home_jpLayout.setHorizontalGroup(
            Home_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home_jpLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addContainerGap(338, Short.MAX_VALUE))
        );
        Home_jpLayout.setVerticalGroup(
            Home_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home_jpLayout.createSequentialGroup()
                .addGroup(Home_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Home_jpLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Home_jpLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel3)))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        main_tabs.addTab("Home", Home_jp);

        funcionarios_jp.setMaximumSize(new java.awt.Dimension(32767000, 32767000));
        funcionarios_jp.setLayout(new java.awt.CardLayout());
        main_tabs.addTab("Funcionários", funcionarios_jp);

        candidaturas_jpanel.setLayout(new java.awt.CardLayout());
        main_tabs.addTab("Candidaturas", candidaturas_jpanel);

        eventos_jp.setLayout(new java.awt.CardLayout());
        main_tabs.addTab("Eventos", eventos_jp);

        doacoes_jp.setLayout(new java.awt.CardLayout());
        main_tabs.addTab("Doações", doacoes_jp);

        doadoresJP.setLayout(new java.awt.CardLayout());
        main_tabs.addTab("Doadores", doadoresJP);

        inventario_jp.setLayout(new java.awt.CardLayout());
        main_tabs.addTab("Inventário", inventario_jp);

        voluntarios_jp.setLayout(new java.awt.CardLayout());
        main_tabs.addTab("Voluntários", voluntarios_jp);

        jMenu1.setText("Menu");

        logout_bt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        logout_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/habitat/PresentationLayer/ICONs/out1.png"))); // NOI18N
        logout_bt.setText("Logout");
        logout_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btActionPerformed(evt);
            }
        });
        jMenu1.add(logout_bt);

        exit_bt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        exit_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/habitat/PresentationLayer/ICONs/exit2.png"))); // NOI18N
        exit_bt.setText("Sair");
        exit_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btActionPerformed(evt);
            }
        });
        jMenu1.add(exit_bt);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_tabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_tabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logout_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logout_btActionPerformed

    private void exit_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        System.exit(0);
    }//GEN-LAST:event_exit_btActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                boolean install = WebLookAndFeel.install();   
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Home_jp;
    private javax.swing.JPanel candidaturas_jpanel;
    private javax.swing.JPanel doacoes_jp;
    private javax.swing.JPanel doadoresJP;
    private javax.swing.JPanel eventos_jp;
    private javax.swing.JMenuItem exit_bt;
    private javax.swing.JPanel funcionarios_jp;
    private javax.swing.JPanel inventario_jp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem logout_bt;
    private javax.swing.JTabbedPane main_tabs;
    private javax.swing.JLabel name_label;
    private javax.swing.JLabel type_label;
    private javax.swing.JPanel voluntarios_jp;
    // End of variables declaration//GEN-END:variables


    public final void init()
    {
        //incializa coisas nice consante o tipo
       this.name_label.setText(this.businessFacade.getActiveUser().getNome());
       this.type_label.setText(this.businessFacade.getActiveUser().getTipo());
       //tabs
       this.funcionarios_jp.add(new FuncionariosJP(businessFacade));
       this.candidaturas_jpanel.add(new CandidaturaJP(businessFacade));
       this.inventario_jp.add(new InventarioJP(businessFacade));
       this.voluntarios_jp.add(new VoluntarioJP(businessFacade));
       this.doacoes_jp.add(new DoacoesJP(businessFacade));
       this.doadoresJP.add(new DoadoresJP(businessFacade));
       this.eventos_jp.add(new EventosJP(businessFacade));
       
        // this.groupBox_func.setVisible(false);
    }

}
