/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.habitat.PresentationLayer.Inventario;

import com.habitat.BusinessLayer.BusinessFacade;
import com.habitat.util.ErrorWindow;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

import java.sql.SQLException;

import javax.swing.JFrame;
import javax.swing.JTable;

/**
 *
 * @author Pedro
 */
public class addMaterialDialog extends javax.swing.JDialog {

    /**
     * Creates new form addMaterialDialog
     */
   private final BusinessFacade bus;
   private final JTable table;
   
    public addMaterialDialog(java.awt.Frame parent, boolean modal,BusinessFacade bus,JTable table) {
        super(parent, modal);
        this.bus = bus;
        this.table = table;
        initComponents();
        this.add_btt.setEnabled(false);    
        initListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        add_btt = new javax.swing.JButton();
        canc_btt = new javax.swing.JButton();
        descricao = new javax.swing.JTextField();
        qtt = new javax.swing.JTextField();
        unid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Descrição :");

        jLabel2.setText("Quantidade :");

        jLabel3.setText("Unidade :");

        add_btt.setText("Adicionar");
        add_btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_bttActionPerformed(evt);
            }
        });

        canc_btt.setText("Cancelar");
        canc_btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canc_bttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(add_btt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(canc_btt))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(descricao)
                            .addComponent(qtt)
                            .addComponent(unid, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(qtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(unid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_btt)
                    .addComponent(canc_btt))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void canc_bttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canc_bttActionPerformed
        // TODO add your handling code here:
        ((JFrame)this.getParent()).dispose();
    }//GEN-LAST:event_canc_bttActionPerformed

    private void add_bttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_bttActionPerformed
        // TODO add your handling code here:
        String desc = this.descricao.getText();
        String unids  =this.unid.getText();
        int qt;
        try{
            qt =  Integer.parseInt(this.qtt.getText());
        }catch(NumberFormatException ex){
            qt = -1;
            new ErrorWindow("quantidade","Quantidade não é um numero" , "error", new JFrame()).wshow();
        }
        if(qt!=-1){
                try {
                    bus.addMaterial(desc,unids,qt);
                } catch (SQLException ex) {

                     new ErrorWindow("Erro",ex.getMessage(), "error", new JFrame()).wshow();
                }
        }
        ((JFrame)this.getParent()).dispose();
    }//GEN-LAST:event_add_bttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addMaterialDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addMaterialDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addMaterialDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addMaterialDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                addMaterialDialog dialog = new addMaterialDialog(new javax.swing.JFrame(), true,null,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btt;
    private javax.swing.JButton canc_btt;
    private javax.swing.JTextField descricao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField qtt;
    private javax.swing.JTextField unid;
    // End of variables declaration//GEN-END:variables
    private KeyListener kl;
    
    private void initListener(){
        this.kl = new KeyListener() {

                    @Override
                    public void keyTyped(KeyEvent e) {
                         if(!unid.getText().isEmpty() && !qtt.getText().isEmpty() && !descricao.getText().isEmpty())
                                 add_btt.setEnabled(true);
                         else add_btt.setEnabled(false);
                    }

                    @Override
                    public void keyPressed(KeyEvent e) {
                        if(!unid.getText().isEmpty() && !qtt.getText().isEmpty() && !descricao.getText().isEmpty())
                                 add_btt.setEnabled(true);
                        else add_btt.setEnabled(false);
                    }

                    @Override
                    public void keyReleased(KeyEvent e) {
                         if(!unid.getText().isEmpty() && !qtt.getText().isEmpty() && !descricao.getText().isEmpty())
                                 add_btt.setEnabled(true);
                         else add_btt.setEnabled(false);
                    }
        };
        
        this.descricao.addKeyListener(kl);
        this.qtt.addKeyListener(kl);
        this.unid.addKeyListener(kl);
    }
}
