/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.habitat.PresentationLayer.Eventos;

import com.habitat.BusinessLayer.BusinessFacade;
import com.habitat.util.ErrorWindow;
import java.awt.Component;
import java.sql.Date;
import java.sql.SQLException;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JTextField;

/**
 *
 * @author filiperibeiro
 */
public class AdicionarEVEN extends javax.swing.JPanel {

    /**
     * Creates new form AdicionarDOA
     */
    private BusinessFacade businessFacade;

    //private TipoDOAListener tipoDOA;

    public AdicionarEVEN(BusinessFacade bus) {
        businessFacade = bus;
        initComponents();
        setVisible(true);
        this.init();
       
        this.submetar_but.setEnabled(true);

    }

    public void clean() {
        for (Component c : this.getComponents()) {
            if (c.getClass() == JTextField.class || c.getClass() == JFormattedTextField.class) {
                ((JTextField) c).setText("");
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nunParticipantes_tf = new javax.swing.JTextField();
        submetar_but = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        data_tf = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        observacoes_ta = new javax.swing.JTextArea();
        tf_valorAnga = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        resp_lb = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Adicionar"));

        jLabel5.setText("Valor Angariado:");

        jLabel7.setText("Nº Participantes:");

        submetar_but.setText("Submeter");
        submetar_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submetar_butActionPerformed(evt);
            }
        });

        jLabel2.setText("Observações:");

        jLabel3.setText("Data:");

        try {
            data_tf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        observacoes_ta.setColumns(20);
        observacoes_ta.setRows(5);
        jScrollPane1.setViewportView(observacoes_ta);

        tf_valorAnga.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel1.setText("(EUR)");

        jLabel4.setText("Responsável:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel3)
                        .addGap(69, 69, 69)
                        .addComponent(data_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7)
                        .addGap(6, 6, 6)
                        .addComponent(nunParticipantes_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(submetar_but))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(resp_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel5)
                                .addGap(5, 5, 5)
                                .addComponent(tf_valorAnga, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(data_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nunParticipantes_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_valorAnga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resp_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addComponent(submetar_but))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submetar_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submetar_butActionPerformed
        // TODO add your handling code here:
        String num = this.nunParticipantes_tf.getText();
        int num_i = Integer.parseInt(num);
        String codProj = null;
        //if(this.codProj_cbox.getSelectedItem()!=null)
        //{
        //    codProj =((String)codProj_cbox.getSelectedItem()).split(":")[1].trim();
        //   
        //} 
        

        String val_s = this.tf_valorAnga.getText();
        float val_f = Float.parseFloat(val_s.replace(",", "."));
        
        String observ = this.observacoes_ta.getText();

        String[] dateArr = this.data_tf.getText().split("/");
        Date date = new Date(Integer.parseInt(dateArr[2]) - 1900, Integer.parseInt(dateArr[1]) - 1, Integer.parseInt(dateArr[0]));

        String fun = this.businessFacade.getActiveUser().getUsername();
        try {
            businessFacade.addEvento(date, val_f, num_i, fun, observ);
        } catch (SQLException ex) {
            new ErrorWindow("Evento", ex.getMessage(), "error", new JFrame()).wshow();
        }

        clean(); 
        this.observacoes_ta.setText("");
    }//GEN-LAST:event_submetar_butActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField data_tf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nunParticipantes_tf;
    private javax.swing.JTextArea observacoes_ta;
    private javax.swing.JLabel resp_lb;
    private javax.swing.JButton submetar_but;
    private javax.swing.JFormattedTextField tf_valorAnga;
    // End of variables declaration//GEN-END:variables


public void init(){
    
    
        String type = this.businessFacade.getActiveUser().getUsername();
        this.resp_lb.setText(type);
        /*try {
            this.codProj_cbox.removeAllItems();
            this.codProj_cbox.addItem(null);
          
                for(String s : businessFacade.getListaIdProjectos()){
                    
                    this.codProj_cbox.addItem("Projeto: "+s);
                }
        } catch (SQLException ex) {
            Logger.getLogger(AdicionarDOA.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }

}
