/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.habitat.PresentationLayer.Eventos;

import com.habitat.BusinessLayer.BusinessFacade;
import com.habitat.BusinessLayer.Doadores.Doador;
import com.habitat.BusinessLayer.Doadores.Empresa;
import com.habitat.BusinessLayer.Eventos.Evento;
import com.habitat.BusinessLayer.Voluntarios.Voluntario;
import com.habitat.PresentationLayer.Doacoes.*;
import com.habitat.PresentationLayer.Doadores.AtualizarDOADOR_empr;
import com.habitat.PresentationLayer.Doadores.AtualizarDOADOR_indiv;
import com.habitat.PresentationLayer.Doadores.ConsultarDOADOR;
import com.habitat.PresentationLayer.Doadores.ConsultarDOADOR_emp;
import com.habitat.PresentationLayer.Doadores.ConsultarDOADOR_indv;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author filiperibeiro
 */
public class ConsultarEVEN extends javax.swing.JPanel implements Observer {

    /**
     * Creates new form ConsultarDAO
     */
    private final BusinessFacade businessFacade;
    private ArrayList<Evento> eventos;
    
    public ConsultarEVEN(BusinessFacade bus) {
        this.businessFacade = bus;
        this.businessFacade.addObserver(this);
        
        try{
            this.eventos = businessFacade.getListaEventos();
            initComponents();
            updateComboBox();
        } catch (SQLException ex) {
            Logger.getLogger(ConsultarDOADOR.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        evento_cb = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar"));

        jLabel1.setText("Evento:");

        jButton3.setText("Consultar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        evento_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        evento_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evento_cbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(evento_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(evento_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(122, 122, 122))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Evento d = (Evento)this.evento_cb.getSelectedItem();
        String type = this.businessFacade.getActiveUser().getTipo(); 
        
        if(type.equals("admin") || type.equals("angariação")){
                    //new AtualizarEVEN(new JFrame(), true, businessFacade).setVisible(true);
            new ConsultarEVENDialog(new JFrame(), true, d,businessFacade).setVisible(true);
            }
        else{
                    new ConsultarEVENDialog(new JFrame(), true, d,businessFacade).setVisible(true);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void evento_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evento_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_evento_cbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox evento_cb;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public void updateComboBox(){
    
        this.evento_cb.removeAllItems(); 
       for(Evento v : eventos)
       {
                this.evento_cb.addItem(v);
       }
    }

    @Override
    public void update(Observable o, Object arg) {
        updateComboBox();
    }
}
