/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.habitat.PresentationLayer.Candidaturas;

import com.habitat.BusinessLayer.BusinessFacade;
import com.habitat.BusinessLayer.Candidaturas.Candidatura;
import java.sql.SQLException;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Pedro
 */
public class ConsultarCand extends javax.swing.JPanel implements Observer{

    /**
     * Creates new form ConsultarCand
     */
    private final BusinessFacade bus;
    public ConsultarCand(BusinessFacade bus) {
        this.bus = bus;
        initComponents();
        this.bus.addObserver(this);
        updateComboBox();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cons_btt = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar"));

        jLabel1.setText("Candidatura :");

        cons_btt.setText("Consultar");
        cons_btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cons_bttActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(cons_btt))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(cons_btt))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cons_bttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cons_bttActionPerformed
        // TODO add your handling code here:
        String tipo = this.bus.getActiveUser().getTipo();
        if(tipo.equals("admin") || tipo.equals("famílias"))
        {
            Candidatura cand = (Candidatura) this.jComboBox1.getSelectedItem();
            if(cand!=null)
            new AtualizarCandidaturaDialog(new JFrame(), true, bus,cand).setVisible(true);
        }
        else{
            Candidatura cand = (Candidatura) this.jComboBox1.getSelectedItem();
            if(cand!=null)
            new ConsultaCandidaturaDialog(new JFrame(), true, bus,cand).setVisible(true);
        }
    }//GEN-LAST:event_cons_bttActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cons_btt;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void updateComboBox() {
       this.jComboBox1.removeAllItems();
        try {
            for(Candidatura c : this.bus.getListaCandidaturas())
            {
                this.jComboBox1.addItem(c);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ConsultarCand.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void update(Observable o, Object arg) {
       updateComboBox();
    }
}
